"""Create Message model

Revision ID: 8a7908ee52a2
Revises: 97ecd6fa8de5
Create Date: 2025-01-22 22:11:06.704621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7908ee52a2'
down_revision = '97ecd6fa8de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
